// SCOS Control Center — Stage 5.2 AI Work Session Manager mock data.
// Static, deterministic display data only. Nothing here is executed and
// nothing is generated at runtime (no Date.now / Math.random / randomUUID);
// ids and timestamps are fixed literals shaped like the Python manager
// output. Mirrors scos/control_center/runtime_registry.py and the
// work_session_manager.py lifecycle.

import type { AgentRuntimeView, AIWorkSessionView } from "./ai-work-session-types";

/** Mirrors the eight built-in runtimes in runtime_registry.py, same order. */
export const AGENT_RUNTIMES: readonly AgentRuntimeView[] = [
  {
    runtimeId: "chatgpt-app",
    agentName: "chatgpt",
    runtimeType: "chatgpt_app",
    displayName: "ChatGPT (desktop app)",
    supportedTaskTypes: [
      "planning",
      "review",
      "audit",
      "status_update",
      "prompt_build",
      "result_summary",
    ],
    enabled: true,
  },
  {
    runtimeId: "chatgpt-web",
    agentName: "chatgpt",
    runtimeType: "chatgpt_web",
    displayName: "ChatGPT (web)",
    supportedTaskTypes: [
      "planning",
      "review",
      "audit",
      "status_update",
      "prompt_build",
      "result_summary",
    ],
    enabled: true,
  },
  {
    runtimeId: "claude-code-cli",
    agentName: "claude_code",
    runtimeType: "claude_code_cli",
    displayName: "Claude Code (CLI)",
    supportedTaskTypes: ["planning", "implementation", "review", "audit", "release_gate"],
    enabled: true,
  },
  {
    runtimeId: "claude-code-vscode",
    agentName: "claude_code",
    runtimeType: "claude_code_vscode",
    displayName: "Claude Code (VS Code extension)",
    supportedTaskTypes: ["planning", "implementation", "review", "audit"],
    enabled: true,
  },
  {
    runtimeId: "codex-cli",
    agentName: "codex",
    runtimeType: "codex_cli",
    displayName: "Codex (CLI)",
    supportedTaskTypes: ["implementation", "review", "audit"],
    enabled: true,
  },
  {
    runtimeId: "codex-app",
    agentName: "codex",
    runtimeType: "codex_app",
    displayName: "Codex (app)",
    supportedTaskTypes: ["implementation", "review"],
    enabled: true,
  },
  {
    runtimeId: "hermes-cli",
    agentName: "hermes",
    runtimeType: "hermes_cli",
    displayName: "Hermes (CLI)",
    supportedTaskTypes: ["planning", "status_update", "result_summary"],
    enabled: true,
  },
  {
    runtimeId: "manual-clipboard",
    agentName: "chatgpt",
    runtimeType: "manual_clipboard",
    displayName: "Manual clipboard handoff",
    supportedTaskTypes: [
      "planning",
      "implementation",
      "review",
      "audit",
      "status_update",
      "prompt_build",
      "result_summary",
      "release_gate",
      "manual_handoff",
    ],
    enabled: true,
  },
];

/** Eight sessions spanning the lifecycle: draft through done, plus blocked/cancelled. */
export const AI_WORK_SESSIONS: readonly AIWorkSessionView[] = [
  {
    sessionId: "session-001",
    task: {
      taskId: "task-001",
      title: "Draft Stage 5.3 scope options",
      taskType: "planning",
      objective: "Outline candidate directions for the next stage",
      inputSummary: "Stage 5.2 acceptance report + open follow-ups",
      sourceStage: "stage-5.2",
      priority: "normal",
    },
    assignment: null,
    status: "draft",
    createdAt: "2026-07-06T09:00:00Z",
    updatedAt: "2026-07-06T09:00:00Z",
    resultSummary: null,
    nextAction: "Assign a runtime before queueing",
  },
  {
    sessionId: "session-002",
    task: {
      taskId: "task-002",
      title: "Implement JSONL session store tests",
      taskType: "implementation",
      objective: "Add append/load round-trip coverage",
      inputSummary: "work_session_store.py draft + contract",
      sourceStage: "stage-5.2",
      priority: "high",
    },
    assignment: {
      assignmentId: "asn-002",
      taskId: "task-002",
      agentName: "codex",
      runtimeId: "codex-cli",
      reason: "Codex CLI supports implementation tasks and is available locally",
      assignedAt: "2026-07-06T09:05:00Z",
    },
    status: "sent_to_agent",
    createdAt: "2026-07-06T09:01:00Z",
    updatedAt: "2026-07-06T09:06:00Z",
    resultSummary: null,
    nextAction: "Waiting for Codex to pick up the prompt",
  },
  {
    sessionId: "session-003",
    task: {
      taskId: "task-003",
      title: "Review Control Center boundary compliance",
      taskType: "review",
      objective: "Confirm Stage 5.2 modules import nothing from scos runtime packages",
      inputSummary: "Diff of scos/control_center/ additions",
      sourceStage: "stage-5.2",
      priority: "high",
    },
    assignment: {
      assignmentId: "asn-003",
      taskId: "task-003",
      agentName: "claude_code",
      runtimeId: "claude-code-cli",
      reason: "Claude Code CLI is already reviewing this diff locally",
      assignedAt: "2026-07-06T09:10:00Z",
    },
    status: "agent_working",
    createdAt: "2026-07-06T09:08:00Z",
    updatedAt: "2026-07-06T09:12:00Z",
    resultSummary: null,
    nextAction: "Agent is producing the review",
  },
  {
    sessionId: "session-004",
    task: {
      taskId: "task-004",
      title: "Summarize Stage 5.2 status for the operator",
      taskType: "status_update",
      objective: "One-paragraph status update for the daily standup note",
      inputSummary: "Current session list + test results",
      sourceStage: "stage-5.2",
      priority: "normal",
    },
    assignment: {
      assignmentId: "asn-004",
      taskId: "task-004",
      agentName: "hermes",
      runtimeId: "hermes-cli",
      reason: "Hermes CLI handles status_update tasks",
      assignedAt: "2026-07-06T08:40:00Z",
    },
    status: "result_ready",
    createdAt: "2026-07-06T08:35:00Z",
    updatedAt: "2026-07-06T08:55:00Z",
    resultSummary:
      "Stage 5.2 models, registry, manager, and store are implemented; " +
      "all Python tests pass; frontend mock panels pending operator review.",
    nextAction: "Operator: review result and mark review_required",
  },
  {
    sessionId: "session-005",
    task: {
      taskId: "task-005",
      title: "Build a routing prompt for the release gate",
      taskType: "prompt_build",
      objective: "Draft the operator-facing prompt for the next release gate run",
      inputSummary: "STAGE4_FINAL_RELEASE_GATE_CONTRACT.md",
      sourceStage: "stage-5.2",
      priority: "low",
    },
    assignment: {
      assignmentId: "asn-005",
      taskId: "task-005",
      agentName: "chatgpt",
      runtimeId: "manual-clipboard",
      reason: "No dedicated ChatGPT integration yet; hand off via clipboard",
      assignedAt: "2026-07-06T07:50:00Z",
    },
    status: "review_required",
    createdAt: "2026-07-06T07:45:00Z",
    updatedAt: "2026-07-06T08:05:00Z",
    resultSummary:
      "Draft prompt pasted back from ChatGPT; needs an operator pass before use.",
    nextAction: "Operator: approve or send back with needs_fix",
  },
  {
    sessionId: "session-006",
    task: {
      taskId: "task-006",
      title: "Audit forbidden-text list for new command types",
      taskType: "audit",
      objective: "Confirm no new command type reintroduces a forbidden marker",
      inputSummary: "command_validation.py FORBIDDEN_COMMAND_TEXT",
      sourceStage: "stage-5.1",
      priority: "normal",
    },
    assignment: {
      assignmentId: "asn-006",
      taskId: "task-006",
      agentName: "claude_code",
      runtimeId: "claude-code-vscode",
      reason: "Quick audit alongside an in-editor review session",
      assignedAt: "2026-07-05T16:00:00Z",
    },
    status: "done",
    createdAt: "2026-07-05T15:55:00Z",
    updatedAt: "2026-07-05T16:20:00Z",
    resultSummary: "No forbidden markers reintroduced; audit closed clean.",
    nextAction: null,
  },
  {
    sessionId: "session-007",
    task: {
      taskId: "task-007",
      title: "Draft a release-gate rollback runbook",
      taskType: "manual_handoff",
      objective: "Write the manual rollback steps for a failed release gate",
      inputSummary: "STAGE4_FINAL_RELEASE_GATE_CONTRACT.md",
      sourceStage: "stage-4.19",
      priority: "urgent",
    },
    assignment: {
      assignmentId: "asn-007",
      taskId: "task-007",
      agentName: "codex",
      runtimeId: "codex-app",
      reason: "Codex app was mid-session when the runtime became unavailable",
      assignedAt: "2026-07-05T11:00:00Z",
    },
    status: "blocked",
    createdAt: "2026-07-05T10:55:00Z",
    updatedAt: "2026-07-05T11:30:00Z",
    resultSummary: "Codex app runtime disconnected mid-task; needs reassignment.",
    nextAction: "Operator: requeue or reassign to a different runtime",
  },
  {
    sessionId: "session-008",
    task: {
      taskId: "task-008",
      title: "Explore auto-generated changelog format",
      taskType: "planning",
      objective: "Spike a changelog generator idea, deprioritized",
      inputSummary: "n/a",
      sourceStage: "stage-5.2",
      priority: "low",
    },
    assignment: null,
    status: "cancelled",
    createdAt: "2026-07-05T09:00:00Z",
    updatedAt: "2026-07-05T09:10:00Z",
    resultSummary: "Deprioritized in favor of Stage 5.2 core work.",
    nextAction: null,
  },
];
