/**
 * Cohort 9A — Truthful read-only Control Center snapshot adapter.
 *
 * This module is the ONLY bridge between the authoritative SCOS backend
 * snapshot (generated by scos/control_center/control_center_snapshot.py and
 * served same-origin via /api/control-center-snapshot) and the cockpit view
 * models. It is LOCAL-ONLY and READ-ONLY:
 *
 *  - It never executes commands, approves/rejects, mutates queues, invokes
 *    HVS, renders, or writes persistence.
 *  - It never calls subprocess, opens sockets, or reaches external network.
 *  - It never imports Python modules or reads sqlite/JSONL directly.
 *  - Demo data is a SEPARATE constant dataset; it is never merged with live
 *    data and is never auto-enabled.
 *
 * Backend section vocabulary (mirrors the Python projection):
 *  - status:  AVAILABLE_WITH_DATA | AVAILABLE_EMPTY | UNAVAILABLE | DEGRADED | ERROR
 *  - available: boolean — false means the source could not be read (do NOT
 *    treat as zero/empty).
 */

export type SectionStatus =
  | "AVAILABLE_WITH_DATA"
  | "AVAILABLE_EMPTY"
  | "UNAVAILABLE"
  | "DEGRADED"
  | "ERROR";

export interface SnapshotSection<T> {
  available: boolean;
  status: SectionStatus;
  data: T | null;
  reason_code: string | null;
  observed_at: string;
}

export interface HealthData {
  health_status: string;
  artifact_count: number;
  event_count: number;
  command_record_count: number;
  audit_record_count: number;
  warning_count: number;
  blocker_count: number;
  source_coverage: [string, string][];
}

export interface QueueData {
  count: number;
  items: { command_id: string; command_type: string; approved_at: string }[];
}

export interface ApprovalData {
  approval_count: number;
  audit_record_count: number | null;
}

export interface EvidenceData {
  event_record_count: number;
  audit_record_count: number;
}

export interface ProjectData {
  state_tables_present: string[];
  has_dedicated_project_model: boolean;
}

export interface ActivityItem {
  activity_id: string;
  activity_type: string;
  status: string;
  summary: string;
  occurred_at: string;
}

export interface ActivityData {
  count: number;
  items: ActivityItem[];
}

export interface ControlCenterSnapshot {
  schema_version: number;
  snapshot_id: string;
  generated_at: string;
  source_mode: "LIVE_LOCAL_READ_ONLY" | "DEMO";
  health: SnapshotSection<HealthData>;
  queue_summary: SnapshotSection<QueueData>;
  approval_summary: SnapshotSection<ApprovalData>;
  project_summary: SnapshotSection<ProjectData>;
  evidence_summary: SnapshotSection<EvidenceData>;
  recent_activity: SnapshotSection<ActivityData>;
  degradation_reasons: string[];
}

export type DataMode = "LIVE" | "DEMO";

/**
 * Map a backend snapshot into cockpit-safe view models.
 * Unavailable sections yield null domain data so the UI can render an
 * explicit "unavailable" state instead of pretending the value is zero.
 */
export interface CockpitView {
  sourceMode: DataMode;
  observedAt: string;
  schemaVersion: number;
  health: {
    available: boolean;
    status: SectionStatus;
    healthStatus: string | null;
    warningCount: number | null;
    blockerCount: number | null;
    reasonCode: string | null;
  };
  queue: {
    available: boolean;
    status: SectionStatus;
    count: number | null;
    items: { command_id: string; command_type: string; approved_at: string }[] | null;
    reasonCode: string | null;
  };
  approvals: {
    available: boolean;
    status: SectionStatus;
    count: number | null;
    reasonCode: string | null;
  };
  evidence: {
    available: boolean;
    status: SectionStatus;
    eventCount: number | null;
    auditCount: number | null;
    reasonCode: string | null;
  };
  projects: {
    available: boolean;
    status: SectionStatus;
    hasDedicatedModel: boolean;
    stateTables: string[];
  };
  activity: {
    available: boolean;
    status: SectionStatus;
    count: number | null;
    items: ActivityItem[] | null;
  };
}

function emptyActivityItems(): ActivityItem[] | null {
  return null;
}

export function mapSnapshotToCockpit(
  snapshot: ControlCenterSnapshot,
  mode: DataMode,
): CockpitView {
  const health = snapshot.health;
  const queue = snapshot.queue_summary;
  const approvals = snapshot.approval_summary;
  const evidence = snapshot.evidence_summary;
  const projects = snapshot.project_summary;
  const activity = snapshot.recent_activity;

  return {
    sourceMode: mode,
    observedAt: snapshot.generated_at,
    schemaVersion: snapshot.schema_version,
    health: {
      available: health.available,
      status: health.status,
      healthStatus: health.data?.health_status ?? null,
      warningCount: health.data?.warning_count ?? null,
      blockerCount: health.data?.blocker_count ?? null,
      reasonCode: health.reason_code ?? null,
    },
    queue: {
      available: queue.available,
      status: queue.status,
      count: queue.data?.count ?? null,
      items: queue.data?.items ?? null,
      reasonCode: queue.reason_code ?? null,
    },
    approvals: {
      available: approvals.available,
      status: approvals.status,
      count: approvals.data?.approval_count ?? null,
      reasonCode: approvals.reason_code ?? null,
    },
    evidence: {
      available: evidence.available,
      status: evidence.status,
      eventCount: evidence.data?.event_record_count ?? null,
      auditCount: evidence.data?.audit_record_count ?? null,
      reasonCode: evidence.reason_code ?? null,
    },
    projects: {
      available: projects.available,
      status: projects.status,
      hasDedicatedModel: projects.data?.has_dedicated_project_model ?? false,
      stateTables: projects.data?.state_tables_present ?? [],
    },
    activity: {
      available: activity.available,
      status: activity.status,
      count: activity.data?.count ?? null,
      items: activity.data?.items ?? emptyActivityItems(),
    },
  };
}

// ---------------------------------------------------------------------------
// DEMO dataset — explicit, separate from live. Never auto-enabled. Never
// merged with live data. Clearly labeled in the UI.
// ---------------------------------------------------------------------------

export const DEMO_SNAPSHOT: ControlCenterSnapshot = {
  schema_version: 1,
  snapshot_id: "ccs-demo",
  generated_at: "2026-07-16T00:00:00Z",
  source_mode: "DEMO",
  health: {
    available: true,
    status: "AVAILABLE_WITH_DATA",
    data: {
      health_status: "healthy",
      artifact_count: 12,
      event_count: 40,
      command_record_count: 3,
      audit_record_count: 31,
      warning_count: 1,
      blocker_count: 0,
      source_coverage: [["state_db", "readable"]],
    },
    reason_code: null,
    observed_at: "2026-07-16T00:00:00Z",
  },
  queue_summary: {
    available: true,
    status: "AVAILABLE_WITH_DATA",
    data: {
      count: 2,
      items: [
        { command_id: "demo-cmd-1", command_type: "render", approved_at: "2026-07-16T00:00:00Z" },
        { command_id: "demo-cmd-2", command_type: "archive", approved_at: "2026-07-16T00:00:00Z" },
      ],
    },
    reason_code: null,
    observed_at: "2026-07-16T00:00:00Z",
  },
  approval_summary: {
    available: true,
    status: "AVAILABLE_WITH_DATA",
    data: { approval_count: 3, audit_record_count: 31 },
    reason_code: null,
    observed_at: "2026-07-16T00:00:00Z",
  },
  project_summary: {
    available: true,
    status: "AVAILABLE_WITH_DATA",
    data: { state_tables_present: ["projects", "approvals", "evidence"], has_dedicated_project_model: false },
    reason_code: null,
    observed_at: "2026-07-16T00:00:00Z",
  },
  evidence_summary: {
    available: true,
    status: "AVAILABLE_WITH_DATA",
    data: { event_record_count: 40, audit_record_count: 31 },
    reason_code: null,
    observed_at: "2026-07-16T00:00:00Z",
  },
  recent_activity: {
    available: true,
    status: "AVAILABLE_WITH_DATA",
    data: {
      count: 2,
      items: [
        { activity_id: "demo-act-1", activity_type: "CERTIFICATION", status: "ok", summary: "Stage 8R certified (demo).", occurred_at: "2026-07-16T00:00:00Z" },
        { activity_id: "demo-act-2", activity_type: "REVIEW", status: "ok", summary: "Stage 8S review ready (demo).", occurred_at: "2026-07-16T00:00:00Z" },
      ],
    },
    reason_code: null,
    observed_at: "2026-07-16T00:00:00Z",
  },
  degradation_reasons: [],
};

export const DEMO_LABEL = "DEMO DATA — NOT LIVE SYSTEM STATE";

/** Resolve the active view model from a data mode. Demo never falls back to live,
 *  and live failure never falls back to demo. */
export function resolveCockpitView(mode: DataMode, live: ControlCenterSnapshot | null): CockpitView {
  if (mode === "DEMO") {
    return mapSnapshotToCockpit(DEMO_SNAPSHOT, "DEMO");
  }
  // LIVE mode: if the live snapshot failed to load, report unavailable states
  // truthfully rather than substituting demo data.
  if (!live) {
    return mapSnapshotToCockpit(unavailableFallback(), "LIVE");
  }
  return mapSnapshotToCockpit(live, "LIVE");
}

function unavailableFallback(): ControlCenterSnapshot {
  const section = {
    available: false,
    status: "UNAVAILABLE" as SectionStatus,
    data: null,
    reason_code: "READ_FAILED",
    observed_at: new Date().toISOString(),
  };
  return {
    schema_version: 1,
    snapshot_id: "ccs-failed",
    generated_at: new Date().toISOString(),
    source_mode: "LIVE_LOCAL_READ_ONLY",
    health: { ...section },
    queue_summary: { ...section },
    approval_summary: { ...section },
    project_summary: { ...section },
    evidence_summary: { ...section },
    recent_activity: { ...section },
    degradation_reasons: ["READ_FAILED"],
  };
}

// ---------------------------------------------------------------------------
// React data hook (client-only). Reads the same-origin read-only transport,
// never reaches external network, never executes commands.
// ---------------------------------------------------------------------------

import { useCallback, useEffect, useRef, useState } from "react";

export type LoadState = "loading" | "ready" | "error";

export interface UseControlCenterData {
  mode: DataMode;
  setMode: (mode: DataMode) => void;
  view: CockpitView;
  loadState: LoadState;
  lastUpdatedAt: string | null;
  refresh: () => void;
  errorMessage: string | null;
}

export function useControlCenterData(initialMode: DataMode = "LIVE"): UseControlCenterData {
  const [mode, setMode] = useState<DataMode>(initialMode);
  const [live, setLive] = useState<ControlCenterSnapshot | null>(null);
  const [loadState, setLoadState] = useState<LoadState>("loading");
  const [lastUpdatedAt, setLastUpdatedAt] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  // Guard against overlapping/out-of-order requests.
  const requestSeq = useRef(0);

  const loadLive = useCallback(() => {
    const seq = ++requestSeq.current;
    setLoadState("loading");
    setErrorMessage(null);
    fetch("/api/control-center-snapshot", { method: "GET", cache: "no-store" })
      .then((res) => {
        if (!res.ok) throw new Error(`http_${res.status}`);
        return res.json();
      })
      .then((payload: ControlCenterSnapshot) => {
        // Ignore stale responses (newer request already in flight).
        if (seq !== requestSeq.current) return;
        setLive(payload);
        setLastUpdatedAt(payload.generated_at ?? new Date().toISOString());
        setLoadState("ready");
      })
      .catch((err: unknown) => {
        if (seq !== requestSeq.current) return;
        setLive(null);
        setErrorMessage(err instanceof Error ? err.message : "unknown_error");
        setLoadState("error");
      });
  }, []);

  useEffect(() => {
    if (mode === "LIVE") {
      loadLive();
    } else {
      // Demo is local; no fetch required.
      setLoadState("ready");
      setErrorMessage(null);
    }
  }, [mode, loadLive]);

  const view = resolveCockpitView(mode, live);
  const refresh = useCallback(() => {
    if (mode === "LIVE") loadLive();
  }, [mode, loadLive]);

  return { mode, setMode, view, loadState, lastUpdatedAt, refresh, errorMessage };
}
