// Static mock data for the SCOS Agent Control Center prototype.
// All timestamps are hardcoded ISO-8601 strings — no runtime clocks are read.
// Nothing here is loaded over the wire; this module is the single source of truth for the UI.

import type {
  Agent,
  HandoffStep,
  MergeItem,
  NextAction,
  ResultItem,
  StageProgress,
  Task,
  TimelineEvent,
} from "./types";

export const AGENTS: Agent[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    role: "Orchestrator",
    status: "active",
    activity: "Sequencing Stage 4.15 tasks and routing work to builders.",
    currentTaskId: "task-01",
    accent: "emerald",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    role: "Builder",
    status: "active",
    activity: "Implementing the mini-audit delivery log module.",
    currentTaskId: "task-02",
    accent: "violet",
  },
  {
    id: "codex",
    name: "Codex",
    role: "Reviewer / Verifier",
    status: "waiting",
    activity: "Verifying the follow-up decision gate change set.",
    currentTaskId: "task-03",
    accent: "sky",
  },
  {
    id: "hermes",
    name: "Hermes",
    role: "Repo Health / Workflow Auditor",
    status: "blocked",
    activity: "Audit paused — waiting on a fixture the builder still owes.",
    currentTaskId: "task-04",
    accent: "amber",
  },
];

export const TASKS: Task[] = [
  {
    id: "task-01",
    code: "SCOS-410",
    title: "Plan Stage 4.15 delivery slice",
    stage: "Stage 4.15",
    status: "in-progress",
    assignee: "chatgpt",
    priority: "high",
    summary:
      "Break Stage 4.15 into buildable slices and assign each to the right agent.",
    checklist: [
      { id: "c1", label: "Draft slice list", done: true },
      { id: "c2", label: "Assign owners", done: true },
      { id: "c3", label: "Confirm acceptance gates", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: false },
      { id: "op4", label: "Codex review complete", done: false },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T09:12:00Z",
  },
  {
    id: "task-02",
    code: "SCOS-411",
    title: "Build mini-audit delivery log",
    stage: "Stage 4.15",
    status: "in-progress",
    assignee: "claude-code",
    priority: "high",
    summary:
      "Implement the first-prospect mini-audit delivery log with a typed contract.",
    checklist: [
      { id: "c1", label: "Define models", done: true },
      { id: "c2", label: "Write append + read API", done: true },
      { id: "c3", label: "Unit tests", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: true },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T10:05:00Z",
  },
  {
    id: "task-03",
    code: "SCOS-408",
    title: "Verify follow-up decision gate",
    stage: "Stage 4.13",
    status: "in-review",
    assignee: "codex",
    priority: "medium",
    summary:
      "Independent verification of the follow-up decision gate before it merges.",
    checklist: [
      { id: "c1", label: "Re-run gate suite", done: true },
      { id: "c2", label: "Check edge cases", done: false },
      { id: "c3", label: "Sign verdict", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: false },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T10:41:00Z",
  },
  {
    id: "task-04",
    code: "SCOS-409",
    title: "Audit repo health for Stage 4.14",
    stage: "Stage 4.14",
    status: "blocked",
    assignee: "hermes",
    priority: "high",
    summary:
      "Workflow audit of the handoff package; blocked until a test fixture lands.",
    blockedReason: "Missing fixture `handoff_sample.json` owed by the builder.",
    checklist: [
      { id: "c1", label: "Lint workflow files", done: true },
      { id: "c2", label: "Validate handoff schema", done: false },
      { id: "c3", label: "Publish audit report", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: false },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: false },
      { id: "op4", label: "Codex review complete", done: false },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T08:30:00Z",
  },
  {
    id: "task-05",
    code: "SCOS-405",
    title: "Approve outreach launch kit",
    stage: "Stage 4.11",
    status: "approved",
    assignee: "chatgpt",
    priority: "medium",
    summary:
      "First-outreach launch kit passed verification and is approved to merge.",
    checklist: [
      { id: "c1", label: "Content review", done: true },
      { id: "c2", label: "Verifier sign-off", done: true },
      { id: "c3", label: "Operator approval", done: true },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: true },
      { id: "op5", label: "Merge decision ready", done: true },
    ],
    updatedAt: "2026-07-03T17:20:00Z",
  },
  {
    id: "task-06",
    code: "SCOS-412",
    title: "Draft delivery-log contract doc",
    stage: "Stage 4.15",
    status: "backlog",
    assignee: "claude-code",
    priority: "low",
    summary:
      "Write the specification note for the mini-audit delivery log contract.",
    checklist: [
      { id: "c1", label: "Outline sections", done: false },
      { id: "c2", label: "Fill invariants", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: false },
      { id: "op3", label: "Builder result received", done: false },
      { id: "op4", label: "Codex review complete", done: false },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T07:55:00Z",
  },
  {
    id: "task-07",
    code: "SCOS-403",
    title: "Ship operator practice lab",
    stage: "Stage 4.10",
    status: "done",
    assignee: "claude-code",
    priority: "medium",
    summary: "Operator practice lab shipped and archived after passing all gates.",
    checklist: [
      { id: "c1", label: "Implement lab", done: true },
      { id: "c2", label: "Verify", done: true },
      { id: "c3", label: "Archive", done: true },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: true },
      { id: "op5", label: "Merge decision ready", done: true },
    ],
    updatedAt: "2026-07-02T14:10:00Z",
  },
  {
    id: "task-08",
    code: "SCOS-413",
    title: "Regression sweep on execution log",
    stage: "Stage 4.12",
    status: "in-review",
    assignee: "codex",
    priority: "low",
    summary:
      "Second-pass regression review of the first-prospect execution log.",
    checklist: [
      { id: "c1", label: "Diff against baseline", done: true },
      { id: "c2", label: "Confirm no drift", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: false },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T11:02:00Z",
  },
  {
    id: "task-09",
    code: "SCOS-414",
    title: "Tidy workflow lint config",
    stage: "Stage 4.15",
    status: "backlog",
    assignee: "hermes",
    priority: "low",
    summary: "Consolidate duplicate workflow lint rules flagged in the last audit.",
    checklist: [
      { id: "c1", label: "Collect duplicate rules", done: false },
      { id: "c2", label: "Propose merged config", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: false },
      { id: "op3", label: "Builder result received", done: false },
      { id: "op4", label: "Codex review complete", done: false },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T06:48:00Z",
  },
];

export const PRIMARY_NEXT_ACTION: NextAction = {
  title: "Hold blocked task until preflight is clean",
  owner: "hermes",
  reason: "Stage 4.14 repo-health audit cannot pass until the missing fixture lands.",
  sourceItem: "SCOS-409 - Stage 4.14 repo-health audit",
  urgency: "high",
  recommendedAction:
    "Keep merge decisions on hold, request the missing fixture, then paste the verification result into Result Inbox.",
};

export const HANDOFF_STEPS: HandoffStep[] = [
  {
    id: "handoff-chatgpt",
    name: "ChatGPT",
    role: "Orchestrator",
    state: "ready",
    message: "Stage slice is sequenced; next prompt is ready to copy.",
  },
  {
    id: "handoff-claude",
    name: "Claude Code",
    role: "Builder",
    state: "working",
    message: "Builder output exists, but one FAIL result needs a fix route.",
  },
  {
    id: "handoff-codex",
    name: "Codex",
    role: "Reviewer",
    state: "needs_review",
    message: "Review PASS/FAIL evidence before any merge approval.",
  },
  {
    id: "handoff-hermes",
    name: "Hermes",
    role: "Repo Health",
    state: "blocked",
    message: "Preflight is blocked by the missing handoff fixture.",
  },
  {
    id: "handoff-merge",
    name: "Merge Decision",
    role: "Operator Gate",
    state: "waiting_result",
    message: "Hold merge until review evidence and fixture status are clean.",
  },
];

export const TIMELINE: TimelineEvent[] = [
  {
    id: "ev-1",
    at: "2026-07-04T11:02:00Z",
    agent: "codex",
    taskId: "task-08",
    message: "Started regression sweep on the execution log.",
    kind: "review",
  },
  {
    id: "ev-2",
    at: "2026-07-04T10:41:00Z",
    agent: "codex",
    taskId: "task-03",
    message: "Re-ran the follow-up decision gate suite — awaiting edge-case pass.",
    kind: "review",
  },
  {
    id: "ev-3",
    at: "2026-07-04T10:05:00Z",
    agent: "claude-code",
    taskId: "task-02",
    message: "Pushed append + read API for the mini-audit delivery log.",
    kind: "info",
  },
  {
    id: "ev-4",
    at: "2026-07-04T08:30:00Z",
    agent: "hermes",
    taskId: "task-04",
    message: "Audit blocked: fixture handoff_sample.json is missing.",
    kind: "warning",
  },
  {
    id: "ev-5",
    at: "2026-07-03T17:20:00Z",
    agent: "chatgpt",
    taskId: "task-05",
    message: "Approved the first-outreach launch kit for merge.",
    kind: "success",
  },
  {
    id: "ev-6",
    at: "2026-07-02T14:10:00Z",
    agent: "claude-code",
    taskId: "task-07",
    message: "Archived the operator practice lab after a clean verification.",
    kind: "success",
  },
];

export const MERGE_QUEUE: MergeItem[] = [
  {
    id: "mq-1",
    taskId: "task-03",
    title: "Follow-up decision gate",
    branch: "feat/followup-decision-gate",
    author: "claude-code",
    verdict: "PASS",
    additions: 214,
    deletions: 36,
    filesChanged: 5,
    decisionGuidance: {
      recommendedDecision: "Hold",
      reason: "PASS verdict is present, but edge-case review is still open.",
      requiredEvidence: "Codex final edge-case sign-off attached to the result.",
      riskLevel: "medium",
    },
    submittedAt: "2026-07-04T10:38:00Z",
  },
  {
    id: "mq-2",
    taskId: "task-02",
    title: "Mini-audit delivery log",
    branch: "feat/mini-audit-delivery-log",
    author: "claude-code",
    verdict: "FAIL",
    additions: 302,
    deletions: 12,
    filesChanged: 6,
    decisionGuidance: {
      recommendedDecision: "Request Fix",
      reason: "Latest result has failing empty-log read tests.",
      requiredEvidence: "Updated builder result plus Codex re-review showing PASS.",
      riskLevel: "high",
    },
    submittedAt: "2026-07-04T10:08:00Z",
  },
  {
    id: "mq-3",
    taskId: "task-05",
    title: "Outreach launch kit",
    branch: "feat/outreach-launch-kit",
    author: "chatgpt",
    verdict: "PASS",
    additions: 128,
    deletions: 4,
    filesChanged: 3,
    decisionGuidance: {
      recommendedDecision: "Approve",
      reason: "Final gate passed and operator approval is complete.",
      requiredEvidence: "PASS result and completed operator checklist.",
      riskLevel: "low",
    },
    submittedAt: "2026-07-03T17:15:00Z",
  },
  {
    id: "mq-4",
    taskId: "task-08",
    title: "Execution log regression fixes",
    branch: "fix/execution-log-regression",
    author: "codex",
    verdict: "PASS",
    additions: 47,
    deletions: 51,
    filesChanged: 2,
    decisionGuidance: {
      recommendedDecision: "Hold",
      reason: "Regression sweep is still in review.",
      requiredEvidence: "Codex confirmation that no drift remains.",
      riskLevel: "medium",
    },
    submittedAt: "2026-07-04T11:00:00Z",
  },
];

export const RESULT_INBOX: ResultItem[] = [
  {
    id: "res-1",
    taskId: "task-02",
    title: "Mini-audit delivery log — unit suite",
    producedBy: "codex",
    verdict: "FAIL",
    summary: "Two tests fail on empty-log reads; append path is otherwise green.",
    metric: "16/18 checks",
    route: {
      status: "FAIL",
      label: "Route to Request Fix",
      destination: "Prompt Builder",
      guidance: "Copy a fix prompt for Claude Code before this can return to review.",
    },
    at: "2026-07-04T10:22:00Z",
  },
  {
    id: "res-2",
    taskId: "task-03",
    title: "Follow-up decision gate — verification",
    producedBy: "codex",
    verdict: "PASS",
    summary: "Gate logic matches the contract; edge cases still under review.",
    metric: "22/22 checks",
    route: {
      status: "NEEDS_REVIEW",
      label: "Route to Codex review",
      destination: "Result Inbox",
      guidance: "Keep the merge held until Codex signs the remaining edge cases.",
    },
    at: "2026-07-04T10:40:00Z",
  },
  {
    id: "res-3",
    taskId: "task-05",
    title: "Outreach launch kit — final gate",
    producedBy: "codex",
    verdict: "PASS",
    summary: "All content and schema gates pass; approved by the operator.",
    metric: "9/9 checks",
    route: {
      status: "PASS",
      label: "Route to Merge Queue",
      destination: "Merge Queue",
      guidance: "Evidence is complete; the operator can approve when ready.",
    },
    at: "2026-07-03T17:12:00Z",
  },
  {
    id: "res-4",
    taskId: "task-04",
    title: "Stage 4.14 repo-health audit",
    producedBy: "hermes",
    verdict: "FAIL",
    summary: "Audit incomplete — a required fixture is missing, so it cannot pass.",
    metric: "1 blocking gap",
    route: {
      status: "BLOCKED",
      label: "Route to Preflight",
      destination: "Operator action",
      guidance: "Hold the merge and request the missing fixture before re-running audit.",
    },
    at: "2026-07-04T08:31:00Z",
  },
];

export const STAGE_PROGRESS: StageProgress = {
  currentStageLabel: "Stage 4.15",
  percentComplete: 62,
  stages: [
    { id: "s10", label: "4.10 Practice Lab", status: "done" },
    { id: "s11", label: "4.11 Launch Kit", status: "done" },
    { id: "s12", label: "4.12 Execution Log", status: "done" },
    { id: "s13", label: "4.13 Decision Gate", status: "done" },
    { id: "s14", label: "4.14 Handoff Package", status: "done" },
    { id: "s15", label: "4.15 Delivery Log", status: "current" },
    { id: "s16", label: "4.16 Reporting", status: "upcoming" },
  ],
};
