// Static mock data for the SCOS Agent Control Center prototype.
// All timestamps are hardcoded ISO-8601 strings; no runtime clocks are read.
// Nothing here is loaded over the wire; this module is the single source of truth for the UI.

import type {
  Agent,
  HandoffStep,
  MergeItem,
  NextAction,
  ResultItem,
  StageProgress,
  Task,
  TimelineEvent,
} from "./types";

export const AGENTS: Agent[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    role: "Orchestrator",
    status: "active",
    activity: "Preparing the Stage 4.17 conversion handoff plan.",
    currentTaskId: "task-01",
    accent: "emerald",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    role: "Builder",
    status: "idle",
    activity: "Ready for the next Control Center v0.1.5 archive slice.",
    currentTaskId: "task-02",
    accent: "violet",
  },
  {
    id: "codex",
    name: "Codex",
    role: "Reviewer / Verifier",
    status: "waiting",
    activity: "Latest v0.1.4 review gate evidence is archived for operator review.",
    currentTaskId: "task-05",
    accent: "sky",
  },
  {
    id: "hermes",
    name: "Hermes",
    role: "Repo Health / Workflow Auditor",
    status: "idle",
    activity: "Repo health is clear after Stage 4.16 and SCOS-409 closure.",
    currentTaskId: "task-03",
    accent: "amber",
  },
];

export const TASKS: Task[] = [
  {
    id: "task-01",
    code: "Stage 4.17",
    title: "First Customer Conversion Handoff",
    stage: "Stage 4.17",
    status: "in-progress",
    assignee: "chatgpt",
    priority: "high",
    summary:
      "Prepare the manual close handoff plan now that Stage 4.16 outcome review is complete.",
    checklist: [
      { id: "c1", label: "Frame conversion handoff objective", done: false },
      { id: "c2", label: "Define manual close checklist", done: false },
      { id: "c3", label: "Confirm acceptance gates", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: false },
      { id: "op3", label: "Builder result received", done: false },
      { id: "op4", label: "Codex review complete", done: false },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T12:15:00Z",
  },
  {
    id: "task-02",
    code: "CC-v0.1.5",
    title: "Commit Evidence History / Review Archive",
    stage: "Control Center v0.1.5",
    status: "backlog",
    assignee: "claude-code",
    priority: "high",
    summary:
      "Add the next frontend-only archive slice for commit evidence history and operator reviews.",
    checklist: [
      { id: "c1", label: "Define archive mock records", done: false },
      { id: "c2", label: "Expose review history UI", done: false },
      { id: "c3", label: "Verify static-only behavior", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: false },
      { id: "op3", label: "Builder result received", done: false },
      { id: "op4", label: "Codex review complete", done: false },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T12:14:00Z",
  },
  {
    id: "task-03",
    code: "Stage 4.16",
    title: "First Prospect Outcome Review",
    stage: "Stage 4.16",
    status: "done",
    assignee: "hermes",
    priority: "medium",
    summary:
      "Outcome review is complete and pushed; this stage is archived as done.",
    checklist: [
      { id: "c1", label: "Review first prospect outcome", done: true },
      { id: "c2", label: "Record closure evidence", done: true },
      { id: "c3", label: "Push Stage 4.16 changes", done: true },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: true },
      { id: "op5", label: "Merge decision ready", done: true },
    ],
    updatedAt: "2026-07-04T12:05:00Z",
  },
  {
    id: "task-04",
    code: "SCOS-409",
    title: "Close handoff fixture audit",
    stage: "Stage 4.16",
    status: "done",
    assignee: "hermes",
    priority: "high",
    summary: "SCOS-409 is closed; handoff_sample.json exists and was pushed.",
    checklist: [
      { id: "c1", label: "Add handoff_sample.json fixture", done: true },
      { id: "c2", label: "Validate handoff schema", done: true },
      { id: "c3", label: "Push closure evidence", done: true },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: true },
      { id: "op5", label: "Merge decision ready", done: true },
    ],
    updatedAt: "2026-07-04T12:02:00Z",
  },
  {
    id: "task-05",
    code: "CC-v0.1.4",
    title: "Operator review and commit gate flow",
    stage: "Control Center v0.1.4",
    status: "done",
    assignee: "codex",
    priority: "medium",
    summary:
      "Control Center v0.1.4 is complete, committed, and deployed to Vercel.",
    checklist: [
      { id: "c1", label: "Add operator review gate", done: true },
      { id: "c2", label: "Commit UI flow", done: true },
      { id: "c3", label: "Deploy to Vercel", done: true },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: true },
      { id: "op5", label: "Merge decision ready", done: true },
    ],
    updatedAt: "2026-07-04T12:00:00Z",
  },
  {
    id: "task-06",
    code: "CC-v0.1.4.1",
    title: "Current State Data Sync",
    stage: "Control Center v0.1.4.1",
    status: "in-review",
    assignee: "claude-code",
    priority: "medium",
    summary:
      "Sync static mock data with the current SCOS project state without adding behavior.",
    checklist: [
      { id: "c1", label: "Update current-state mock data", done: true },
      { id: "c2", label: "Run lint and build", done: false },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: false },
      { id: "op5", label: "Merge decision ready", done: false },
    ],
    updatedAt: "2026-07-04T12:16:00Z",
  },
  {
    id: "task-07",
    code: "Stage 4.15",
    title: "Delivery Log",
    stage: "Stage 4.15",
    status: "done",
    assignee: "claude-code",
    priority: "medium",
    summary: "Stage 4.15 is complete and archived before the Stage 4.16 outcome review.",
    checklist: [
      { id: "c1", label: "Implement delivery log", done: true },
      { id: "c2", label: "Verify", done: true },
      { id: "c3", label: "Archive", done: true },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: true },
      { id: "op5", label: "Merge decision ready", done: true },
    ],
    updatedAt: "2026-07-04T11:40:00Z",
  },
  {
    id: "task-08",
    code: "SCOS-408",
    title: "Follow-up decision gate",
    stage: "Stage 4.13",
    status: "done",
    assignee: "codex",
    priority: "low",
    summary: "Follow-up decision gate verification is complete and archived.",
    checklist: [
      { id: "c1", label: "Diff against baseline", done: true },
      { id: "c2", label: "Confirm no drift", done: true },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: true },
      { id: "op5", label: "Merge decision ready", done: true },
    ],
    updatedAt: "2026-07-04T10:41:00Z",
  },
  {
    id: "task-09",
    code: "SCOS-405",
    title: "Outreach launch kit",
    stage: "Stage 4.11",
    status: "done",
    assignee: "chatgpt",
    priority: "low",
    summary: "First-outreach launch kit passed verification and is archived.",
    checklist: [
      { id: "c1", label: "Content review", done: true },
      { id: "c2", label: "Verifier sign-off", done: true },
    ],
    operatorChecklist: [
      { id: "op1", label: "Preflight clean", done: true },
      { id: "op2", label: "Prompt prepared", done: true },
      { id: "op3", label: "Builder result received", done: true },
      { id: "op4", label: "Codex review complete", done: true },
      { id: "op5", label: "Merge decision ready", done: true },
    ],
    updatedAt: "2026-07-03T17:20:00Z",
  },
];

export const PRIMARY_NEXT_ACTION: NextAction = {
  title: "Prepare Stage 4.17 conversion handoff plan",
  owner: "chatgpt",
  reason:
    "Stage 4.16 outcome review is complete; next step is manual close preparation.",
  sourceItem: "Stage 4.17 - First Customer Conversion Handoff",
  urgency: "high",
  recommendedAction:
    "Draft the conversion handoff plan, define the manual close checklist, and prepare the next builder prompt.",
};

export const HANDOFF_STEPS: HandoffStep[] = [
  {
    id: "handoff-chatgpt",
    name: "ChatGPT",
    role: "Orchestrator",
    state: "ready",
    message: "Stage 4.17 planning target is ready to sequence.",
  },
  {
    id: "handoff-claude",
    name: "Claude Code",
    role: "Builder",
    state: "ready",
    message: "Builder is ready for the Stage 4.17 or v0.1.5 static slice.",
  },
  {
    id: "handoff-codex",
    name: "Codex",
    role: "Reviewer",
    state: "approved",
    message: "Latest v0.1.4 review gate evidence is PASS.",
  },
  {
    id: "handoff-hermes",
    name: "Hermes",
    role: "Repo Health",
    state: "approved",
    message: "SCOS-409 is closed and handoff_sample.json is present.",
  },
  {
    id: "handoff-merge",
    name: "Merge Decision",
    role: "Operator Gate",
    state: "ready",
    message: "No default blocker is pending; next work is planning.",
  },
];

export const TIMELINE: TimelineEvent[] = [
  {
    id: "ev-1",
    at: "2026-07-04T12:16:00Z",
    agent: "chatgpt",
    taskId: "task-01",
    message: "Stage 4.17 planning is ready for the conversion handoff.",
    kind: "info",
  },
  {
    id: "ev-2",
    at: "2026-07-04T12:14:00Z",
    agent: "claude-code",
    taskId: "task-02",
    message: "Control Center v0.1.5 archive feature is ready for planning.",
    kind: "info",
  },
  {
    id: "ev-3",
    at: "2026-07-04T12:00:00Z",
    agent: "claude-code",
    taskId: "task-05",
    message: "Control Center v0.1.4 deployed to Vercel.",
    kind: "success",
  },
  {
    id: "ev-4",
    at: "2026-07-04T11:58:00Z",
    agent: "codex",
    taskId: "task-05",
    message:
      "Control Center v0.1.4 committed as 798c88b feat(ui): add operator review and commit gate flow.",
    kind: "success",
  },
  {
    id: "ev-5",
    at: "2026-07-04T11:50:00Z",
    agent: "hermes",
    taskId: "task-03",
    message: "Stage 4.16 completed and pushed.",
    kind: "success",
  },
  {
    id: "ev-6",
    at: "2026-07-04T11:44:00Z",
    agent: "claude-code",
    taskId: "task-04",
    message: "SCOS-409 fixture handoff_sample.json added and pushed.",
    kind: "success",
  },
];

export const MERGE_QUEUE: MergeItem[] = [
  {
    id: "mq-1",
    taskId: "task-05",
    title: "Control Center v0.1.4 deployed",
    branch: "main",
    author: "claude-code",
    verdict: "PASS",
    additions: 0,
    deletions: 0,
    filesChanged: 0,
    decisionGuidance: {
      recommendedDecision: "Approve",
      reason: "v0.1.4 is complete, committed, and deployed.",
      requiredEvidence: "Commit 798c88b and Vercel deployment evidence.",
      riskLevel: "low",
    },
    submittedAt: "2026-07-04T12:00:00Z",
  },
];

export const RESULT_INBOX: ResultItem[] = [
  {
    id: "res-1",
    taskId: "task-05",
    title: "Control Center v0.1.4 deployment",
    producedBy: "codex",
    verdict: "PASS",
    summary: "v0.1.4 review gate flow is complete, committed, and deployed.",
    metric: "Deployed",
    route: {
      status: "PASS",
      label: "Route to Archive",
      destination: "Merge Queue",
      guidance: "Evidence is complete; no default blocker is pending.",
    },
    at: "2026-07-04T12:00:00Z",
  },
  {
    id: "res-2",
    taskId: "task-03",
    title: "Stage 4.16 outcome review",
    producedBy: "hermes",
    verdict: "PASS",
    summary: "Stage 4.16 is complete and pushed.",
    metric: "Complete",
    route: {
      status: "PASS",
      label: "Route to Archive",
      destination: "Task Board",
      guidance: "Stage is archived; proceed to Stage 4.17 planning.",
    },
    at: "2026-07-04T11:50:00Z",
  },
  {
    id: "res-3",
    taskId: "task-04",
    title: "SCOS-409 handoff fixture",
    producedBy: "hermes",
    verdict: "PASS",
    summary: "handoff_sample.json fixture exists and was pushed; SCOS-409 is closed.",
    metric: "Closed",
    route: {
      status: "PASS",
      label: "Route to Archive",
      destination: "Task Board",
      guidance: "No blocked decision remains for SCOS-409.",
    },
    at: "2026-07-04T11:44:00Z",
  },
];

export const STAGE_PROGRESS: StageProgress = {
  currentStageLabel: "Stage 4.17",
  percentComplete: 84,
  stages: [
    { id: "s11", label: "4.11 Launch Kit", status: "done" },
    { id: "s12", label: "4.12 Execution Log", status: "done" },
    { id: "s13", label: "4.13 Decision Gate", status: "done" },
    { id: "s14", label: "4.14 Handoff Package", status: "done" },
    { id: "s15", label: "4.15 Delivery Log", status: "done" },
    { id: "s16", label: "4.16 Outcome Review", status: "done" },
    { id: "s17", label: "4.17 Conversion Handoff", status: "current" },
  ],
};
