import type { OperatorCommandViewSnapshot } from "./operator-command-view-types";

const checkedAt = "2026-07-10T01:00:00Z";

const statePath = "scos/work/control_center/state/control_center.sqlite3";
const eventPath = "scos/work/control_center/events/command_events.jsonl";

export const operatorCommandViewSnapshot: OperatorCommandViewSnapshot = {
  snapshotId: "ocvs-stage76-static",
  checkedAt,
  readinessScore: 72,
  goNoGo: "NO_GO",
  accepted: false,
  totals: {
    pending: 1,
    approved: 1,
    denied: 1,
    missingApproval: 1,
    executed: 1,
    blocked: 3,
    audited: 5,
  },
  warnings: ["One command has optional result evidence unavailable in the fixture."],
  blockers: [
    "Denied command is terminal for its current action instance.",
    "Missing approval command is terminal for its current action instance.",
    "Blocked command cannot bypass validation evidence.",
  ],
  views: [
    {
      viewId: "ocv-pending",
      checkedAt,
      commandId: "cmd-stage76-pending",
      commandType: "RUN_SECURITY_SCAN",
      approval: {
        commandId: "cmd-stage76-pending",
        approvalState: "pending",
        terminal: false,
        humanReadableStatus: "pending",
        requiredOperatorAction: "Review approval evidence manually.",
        evidenceReferences: [
          {
            referenceId: "ref-pending-approval",
            referenceType: "approval",
            sourceStage: "Stage 6.6",
            path: statePath,
            exists: true,
            readable: true,
            digest: "8d7d0c1a",
          },
        ],
      },
      execution: {
        evidenceId: "evid-pending",
        commandId: "cmd-stage76-pending",
        executionState: "not_executed",
        approvalState: "pending",
        auditState: "audited",
        eventState: "present",
        summary: "Pending command evidence is visible; no action is performed here.",
        references: [],
        metadata: [["source", "static-fixture"]],
      },
      warnings: [],
      blockers: [],
      nextManualAction: "Review approval evidence manually.",
    },
    {
      viewId: "ocv-approved",
      checkedAt,
      commandId: "cmd-stage76-approved",
      commandType: "RUN_SMOKE_CHECK",
      approval: {
        commandId: "cmd-stage76-approved",
        approvalState: "approved",
        terminal: false,
        humanReadableStatus: "approved",
        requiredOperatorAction: "Inspect execution evidence; Stage 7.6 is display-only.",
        evidenceReferences: [
          {
            referenceId: "ref-approved-approval",
            referenceType: "approval",
            sourceStage: "Stage 6.6",
            path: statePath,
            exists: true,
            readable: true,
            digest: "4ab4c0de",
          },
        ],
      },
      execution: {
        evidenceId: "evid-approved",
        commandId: "cmd-stage76-approved",
        executionState: "not_executed",
        approvalState: "approved",
        auditState: "audited",
        eventState: "present",
        summary: "Approval exists, but this panel does not start work.",
        references: [],
        metadata: [["source", "static-fixture"]],
      },
      warnings: [],
      blockers: [],
      nextManualAction: "Inspect execution evidence; Stage 7.6 is display-only.",
    },
    {
      viewId: "ocv-denied",
      checkedAt,
      commandId: "cmd-stage76-denied",
      commandType: "RUN_RELEASE_CHECK",
      approval: {
        commandId: "cmd-stage76-denied",
        approvalState: "denied",
        terminal: true,
        humanReadableStatus: "denied",
        requiredOperatorAction: "Create a new command draft manually if needed.",
        evidenceReferences: [
          {
            referenceId: "ref-denied-audit",
            referenceType: "audit",
            sourceStage: "Stage 6.6",
            path: statePath,
            exists: true,
            readable: true,
            digest: "1eafcafe",
          },
        ],
      },
      execution: {
        evidenceId: "evid-denied",
        commandId: "cmd-stage76-denied",
        executionState: "blocked_denied",
        approvalState: "denied",
        auditState: "audited",
        eventState: "present",
        summary: "Denied command is terminal for this action instance.",
        references: [],
        metadata: [["source", "static-fixture"]],
      },
      warnings: [],
      blockers: ["Denied commands cannot be used as execution evidence."],
      nextManualAction: "Create a new command draft manually if needed.",
    },
    {
      viewId: "ocv-missing",
      checkedAt,
      commandId: "cmd-stage76-missing",
      commandType: "RUN_STAGE4_FINAL_GATE",
      approval: {
        commandId: "cmd-stage76-missing",
        approvalState: "missing_approval",
        terminal: true,
        humanReadableStatus: "missing approval",
        requiredOperatorAction: "Create a fresh approved command instance before execution.",
        evidenceReferences: [
          {
            referenceId: "ref-missing-approval",
            referenceType: "approval",
            sourceStage: "Stage 6.6",
            path: statePath,
            exists: false,
            readable: false,
            digest: null,
          },
        ],
      },
      execution: {
        evidenceId: "evid-missing",
        commandId: "cmd-stage76-missing",
        executionState: "blocked_missing_approval",
        approvalState: "missing_approval",
        auditState: "missing",
        eventState: "missing",
        summary: "Missing approval blocks the current command instance.",
        references: [],
        metadata: [["source", "static-fixture"]],
      },
      warnings: [],
      blockers: ["Approval evidence is required before any execution path can be trusted."],
      nextManualAction: "Create a fresh approved command instance before execution.",
    },
    {
      viewId: "ocv-executed",
      checkedAt,
      commandId: "cmd-stage76-executed",
      commandType: "GENERATE_STATUS_SNAPSHOT",
      approval: {
        commandId: "cmd-stage76-executed",
        approvalState: "executed",
        terminal: true,
        humanReadableStatus: "executed",
        requiredOperatorAction: "Inspect audit and event evidence for the completed action instance.",
        evidenceReferences: [
          {
            referenceId: "ref-executed-event",
            referenceType: "event",
            sourceStage: "Stage 6.4",
            path: eventPath,
            exists: true,
            readable: true,
            digest: "9f00d123",
          },
        ],
      },
      execution: {
        evidenceId: "evid-executed",
        commandId: "cmd-stage76-executed",
        executionState: "executed",
        approvalState: "executed",
        auditState: "audited",
        eventState: "present",
        summary: "Execution, event, and audit evidence are visible.",
        references: [],
        metadata: [["source", "static-fixture"]],
      },
      warnings: ["Optional result artifact is not present in this fixture."],
      blockers: [],
      nextManualAction: "Inspect audit and event evidence for the completed action instance.",
    },
    {
      viewId: "ocv-blocked",
      checkedAt,
      commandId: "cmd-stage76-blocked",
      commandType: "UNKNOWN_COMMAND",
      approval: {
        commandId: "cmd-stage76-blocked",
        approvalState: "blocked",
        terminal: true,
        humanReadableStatus: "blocked",
        requiredOperatorAction: "Resolve the displayed blocker without bypassing approval.",
        evidenceReferences: [
          {
            referenceId: "ref-blocked-validation",
            referenceType: "state",
            sourceStage: "Stage 6.2",
            path: "Command API validation result",
            exists: true,
            readable: true,
            digest: null,
          },
        ],
      },
      execution: {
        evidenceId: "evid-blocked",
        commandId: "cmd-stage76-blocked",
        executionState: "blocked_validation_failed",
        approvalState: "blocked",
        auditState: "audited",
        eventState: "present",
        summary: "Command type is blocked by validation evidence.",
        references: [],
        metadata: [["source", "static-fixture"]],
      },
      warnings: [],
      blockers: ["Validation rejected the command type."],
      nextManualAction: "Resolve the displayed blocker without bypassing approval.",
    },
  ],
};
