// SCOS Control Center - Stage 5.5 Operator Packet Review mock data.
// Static deterministic data only. No runtime generation, storage, backend,
// clipboard, or dispatch behavior.

import type { OperatorPacketReviewView } from "./operator-packet-review-types";

const SAFE_CHECKS = [
  {
    checkName: "packet_id_present",
    status: "success",
    severity: "info",
    errorDetail: null,
  },
  {
    checkName: "metadata_safe",
    status: "success",
    severity: "info",
    errorDetail: null,
  },
  {
    checkName: "packet_paths_local",
    status: "success",
    severity: "info",
    errorDetail: null,
  },
] as const;

const WARNING_CHECKS = [
  ...SAFE_CHECKS,
  {
    checkName: "target_runtime_known",
    status: "skipped",
    severity: "warning",
    errorDetail: "Runtime type id is not in the local runtime registry.",
  },
] as const;

export const OPERATOR_PACKET_REVIEWS: readonly OperatorPacketReviewView[] = [
  {
    reviewId: "opr-55-chatgpt-claude",
    packetId: "pp-55-chatgpt-plan",
    resultPacketId: null,
    packetType: "implementation_prompt",
    sourceAgent: "chatgpt",
    targetAgent: "claude_code",
    targetRuntimeId: "claude_code_cli",
    routingDecisionId: "rd-55-plan-impl",
    routingReason: "ChatGPT plan is ready for Claude Code implementation.",
    routingPriority: "normal",
    verdict: null,
    title: "ChatGPT -> Claude Code prompt awaiting approval",
    objective: "Operator reviews the implementation prompt before handoff.",
    requiredDecision: "approve",
    status: "pending",
    checks: WARNING_CHECKS,
    handoffPreview: null,
    operatorNote: "Approve only after confirming the prompt is local-only and scoped.",
  },
  {
    reviewId: "opr-55-claude-codex",
    packetId: "pp-55-claude-impl",
    resultPacketId: "rp-55-claude-pass",
    packetType: "implementation_result",
    sourceAgent: "claude_code",
    targetAgent: "codex",
    targetRuntimeId: "codex_cli",
    routingDecisionId: "rd-55-impl-review",
    routingReason: "Claude Code reports PASS; route to Codex review.",
    routingPriority: "normal",
    verdict: "PASS",
    title: "Claude Code result -> Codex review awaiting approval",
    objective: "Operator confirms the result packet is safe to review.",
    requiredDecision: "approve",
    status: "pending",
    checks: WARNING_CHECKS,
    handoffPreview: null,
    operatorNote: "No review packet is sent until the operator approves.",
  },
  {
    reviewId: "opr-55-codex-needs-fix",
    packetId: "pp-55-codex-review",
    resultPacketId: "rp-55-codex-needs-fix",
    packetType: "review_result",
    sourceAgent: "codex",
    targetAgent: "claude_code",
    targetRuntimeId: "claude_code_cli",
    routingDecisionId: "rd-55-fix-loop",
    routingReason: "Codex marked NEEDS_FIX; prepare a manual fix handoff.",
    routingPriority: "high",
    verdict: "NEEDS_FIX",
    title: "Codex NEEDS_FIX -> Claude Code manual handoff",
    objective: "Operator prepares the local handoff package for a fix pass.",
    requiredDecision: "manual_handoff",
    status: "manual_handoff_prepared",
    checks: WARNING_CHECKS,
    handoffPreview: {
      handoffId: "oph-55-needs-fix",
      targetAgent: "claude_code",
      targetRuntimeId: "claude_code_cli",
      handoffMode: "manual_clipboard",
      promptPreview:
        "Fix the Stage 5.5 review store edge case reported by Codex. Keep changes scoped and run the focused tests.",
      contextSummaryPreview:
        "Source result rp-55-codex-needs-fix found one missing malformed JSONL test.",
      steps: [
        "Open the target AI/runtime manually.",
        "Paste or provide the prompt manually.",
        "Wait for the AI result.",
        "Save the result back into SCOS as a ResultPacket.",
        "Do not let the AI commit/push without operator approval.",
      ],
      manifestPath: "scos/work/control_center/manual_handoffs/handoff_oph-55-needs-fix/handoff_manifest.json",
    },
    operatorNote: "Prepared means local package preview only; SCOS did not copy or send it.",
  },
  {
    reviewId: "opr-55-hermes-blocked",
    packetId: "pp-55-hermes-audit",
    resultPacketId: "rp-55-hermes-blocked",
    packetType: "audit_result",
    sourceAgent: "hermes",
    targetAgent: "operator",
    targetRuntimeId: "manual_review_only",
    routingDecisionId: "rd-55-blocked",
    routingReason: "Hermes BLOCKED requires human judgment before any next step.",
    routingPriority: "urgent",
    verdict: "BLOCKED",
    title: "Hermes BLOCKED -> operator blocked review",
    objective: "Operator records the block and prevents dispatch.",
    requiredDecision: "blocked",
    status: "blocked",
    checks: [
      ...SAFE_CHECKS,
      {
        checkName: "blocked_by_critical_check",
        status: "failure",
        severity: "critical",
        errorDetail: "Repo-health audit blocked release progression.",
      },
    ],
    handoffPreview: null,
    operatorNote: "Blocked packets stay local until a human clears the reason.",
  },
  {
    reviewId: "opr-55-rejected-routing",
    packetId: "pp-55-wrong-target",
    resultPacketId: "rp-55-wrong-target",
    packetType: "review_result",
    sourceAgent: "codex",
    targetAgent: "hermes",
    targetRuntimeId: "hermes_cli",
    routingDecisionId: "rd-55-rejected",
    routingReason: "Routing target does not match the operator's intended fix loop.",
    routingPriority: "normal",
    verdict: "NEEDS_FIX",
    title: "Rejected routing decision",
    objective: "Operator rejects an unsafe or incorrect route.",
    requiredDecision: "reject",
    status: "rejected",
    checks: SAFE_CHECKS,
    handoffPreview: null,
    operatorNote: "Rejected routing is recorded locally and nothing is dispatched.",
  },
  {
    reviewId: "opr-55-approved-handoff",
    packetId: "pp-55-approved-manual",
    resultPacketId: "rp-55-approved-manual",
    packetType: "manual_handoff_result",
    sourceAgent: "operator",
    targetAgent: "chatgpt",
    targetRuntimeId: "chatgpt_app",
    routingDecisionId: "rd-55-approved-handoff",
    routingReason: "Operator approved a prepared local-only status-summary handoff.",
    routingPriority: "low",
    verdict: "PASS_WITH_WARNINGS",
    title: "Approved manual handoff package preview",
    objective: "Show a completed local handoff package without executing it.",
    requiredDecision: "manual_handoff",
    status: "manual_handoff_prepared",
    checks: WARNING_CHECKS,
    handoffPreview: {
      handoffId: "oph-55-approved-summary",
      targetAgent: "chatgpt",
      targetRuntimeId: "chatgpt_app",
      handoffMode: "manual_clipboard",
      promptPreview:
        "Summarize Stage 5.5 progress for the operator. Mention tests, constraints, and no-dispatch status.",
      contextSummaryPreview:
        "Package references Stage 5.5 review result and local test evidence only.",
      steps: [
        "Open the target AI/runtime manually.",
        "Paste or provide the prompt manually.",
        "Wait for the AI result.",
        "Save the result back into SCOS as a ResultPacket.",
        "Do not let the AI commit/push without operator approval.",
      ],
      manifestPath: "scos/work/control_center/manual_handoffs/handoff_oph-55-approved-summary/handoff_manifest.json",
    },
    operatorNote: "The package is ready for the operator to use outside SCOS.",
  },
];
