
export type IntakeStatus = "DRAFT"|"NEEDS_INPUT"|"READY_FOR_REVIEW"|"BLOCKED"|"READY_TO_CREATE"|"CREATING"|"CREATED"|"CREATION_FAILED_CONFIRMED"|"CREATION_OUTCOME_UNKNOWN";
export interface IntakeFinding { field:string; status:string; message:string; why_required:string; operator_action:string; blocked_effect:string; }
export interface IntakeAsset { asset_id:string; safe_name:string; sha256:string; size_bytes:number; status:string; rights_required:boolean; safe_reference:string; }
// --- Cohort 10K plain-language Brief Studio projection (server-computed, read-only) ---
export type BriefSectionState = "READY"|"NEEDS_INFORMATION"|"BLOCKED_FOR_RIGHTS"|"BLOCKED_FOR_PRIVACY"|"BLOCKED_FOR_ASSETS"|"CREATED"|"CREATION_OUTCOME_UNKNOWN";
export interface BriefRecommendation { field:string; value:string; label:string; reason:string; }
export interface BriefSection { id:string; heading:string; state:BriefSectionState; blocking:boolean; why_it_matters:string; how_to_resolve:string; detail:string; recommended:BriefRecommendation[]; }
export interface BriefAssetSummary { available:number; needs_review:number; unsupported:number; missing:number; names:string[]; }
export interface BriefResolvedOutput { selected_template:string; target_platform:string; output_profile:string; duration:string; }
export interface BriefProjection { schema_version:string; sections:BriefSection[]; ready_count:number; total_count:number; readiness_label:string; overall:BriefSectionState; answers:Record<string,string>; raw_answers:Record<string,string>; recommendations:BriefRecommendation[]; assets:BriefAssetSummary; resolved_output:BriefResolvedOutput; will_not_do:string[]; }
export interface GuidedIntakeDraft { schema_version:string; draft_id:string; status:IntakeStatus; safe_project_title:string; selected_template:string; target_platform:string; output_profile:string; duration:string; deadline:string; commercial_reference:string; asset_references:IntakeAsset[]; consent_state:string; consent_evidence_reference:string; consent_evidence_sha256:string; explicit_consent_confirmed:boolean; rights_answers:Record<string,string>; privacy_answers:Record<string,string>; derived_classification:string; retention_policy:string; external_action_restrictions:Record<string,string>; validation_findings:IntakeFinding[]; generated:Record<string,unknown>&{brief?:BriefProjection}; created_at:string; updated_at:string; revision:number; pilot_safe_id:string; project_safe_id:string; admission_packet_sha256:string; brief_mode?:boolean; brief_answers?:Record<string,string>; }
export interface IntakeResponse { ok:boolean; error_code:string|null; detail:string|null; draft:GuidedIntakeDraft|null; replay?:boolean; pilot_safe_id?:string; project_safe_id?:string; admission_packet_sha256?:string; next_safe_action?:string; }
