import type {
  CommitApprovalDecisionView,
  PushApprovalDecisionView,
  PushProposalView,
  PushReadinessSnapshotView,
} from "@/lib/git-approval-types";

export function PushApprovalPanel({
  readiness,
  commitDecision,
  proposal,
  decision,
}: {
  readiness: PushReadinessSnapshotView;
  commitDecision: CommitApprovalDecisionView | null;
  proposal: PushProposalView | null;
  decision: PushApprovalDecisionView | null;
}) {
  const commitApproved = commitDecision?.decision === "approved";
  const readyToPropose =
    commitApproved &&
    readiness.aheadBy >= 1 &&
    readiness.behindBy === 0 &&
    !readiness.hasRemoteOnlyCommits &&
    readiness.workingTreeClean;

  return (
    <section className="rounded-card border border-border bg-surface p-4">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h2 className="text-sm font-semibold text-ink">Push Approval</h2>
          <p className="mt-1 text-xs text-ink-faint">
            Proposal only — nothing here runs <code>git push</code>. Force
            push, tags, and releases can never be represented here.
          </p>
        </div>
        <span
          className={
            proposal
              ? "rounded-full bg-status-review/15 px-2 py-0.5 text-[10px] font-semibold text-status-review ring-1 ring-inset ring-status-review/30"
              : "rounded-full bg-surface-2 px-2 py-0.5 text-[10px] font-semibold text-ink-faint ring-1 ring-inset ring-border"
          }
        >
          {proposal ? "push proposal ready" : "locked until commit approved"}
        </span>
      </div>

      <div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-lg border border-border-soft bg-surface-2/40 px-3 py-2">
          <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-faint">Ahead</p>
          <p className="mt-1 text-xs font-semibold text-ink">{readiness.aheadBy}</p>
        </div>
        <div className="rounded-lg border border-border-soft bg-surface-2/40 px-3 py-2">
          <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-faint">Behind</p>
          <p className="mt-1 text-xs font-semibold text-ink">{readiness.behindBy}</p>
        </div>
        <div className="rounded-lg border border-border-soft bg-surface-2/40 px-3 py-2">
          <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-faint">
            Remote
          </p>
          <p className="mt-1 font-mono text-xs text-ink">origin</p>
        </div>
        <div className="rounded-lg border border-border-soft bg-surface-2/40 px-3 py-2">
          <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-faint">
            Refspec
          </p>
          <p className="mt-1 font-mono text-xs text-ink">main</p>
        </div>
      </div>

      <div className="mt-3">
        <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-faint">
          Proposed command
        </p>
        <pre className="mt-1 overflow-auto rounded-lg border border-border-soft bg-surface-2/50 p-3 font-mono text-[11px] text-ink">
{proposal ? proposal.proposedCommand : "git push origin main"}
        </pre>
        <p className="mt-1 text-[11px] text-ink-faint">
          Force push, <code>--force-with-lease</code>, tags, and releases are
          never generated by this stage.
        </p>
      </div>

      <div className="mt-4 rounded-lg border border-dashed border-border-soft bg-surface-2/30 p-3">
        <p className="text-[11px] text-ink-faint">
          {readyToPropose
            ? "Push proposal is ready for operator review (inert mock)."
            : "Approve Push is disabled until the commit approval decision above is 'approved'."}
        </p>
        <button
          type="button"
          disabled
          className="mt-2 cursor-not-allowed rounded-full border border-border-soft px-3 py-1 text-[10px] font-semibold text-ink-faint opacity-60"
        >
          Approve Push (disabled)
        </button>
      </div>

      {decision ? (
        <div className="mt-3 rounded-lg border border-border-soft bg-surface-2/40 p-3">
          <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-faint">
            Recorded push decision
          </p>
          <p className="mt-1 text-xs text-ink">
            <span className="font-semibold">{decision.decision}</span> by{" "}
            {decision.decidedBy} — {decision.reason}
          </p>
          {decision.manualCommand ? (
            <pre className="mt-2 overflow-auto rounded bg-surface p-2 font-mono text-[11px] text-ink-muted">
{decision.manualCommand}
            </pre>
          ) : null}
        </div>
      ) : null}
    </section>
  );
}
