"""SCOS Stage 5.1 local Control Center command bridge.

First local-first bridge between the SCOS Control Center concept and the local
SCOS command system: draft -> validate -> operator approval -> JSONL queue ->
allowlisted local runner -> JSONL event log.

Stage 5.1 note: exports are resolved lazily via PEP 562 module ``__getattr__``
(mirroring ``scos.commercial``) so importing this package never eagerly pulls
in sibling modules. The package is stdlib-only and never imports
``scos.commercial`` or ``scos.knowledge`` in-process.

Local-first, deterministic, stdlib-only. No clock, no random, no uuid,
no network, no server, no database.
"""

from __future__ import annotations

from typing import Any

# name -> sibling module that defines it (imported on first access only)
_LAZY_EXPORTS: dict[str, str] = {
    "CONTROL_CENTER_COMMAND_SCHEMA_VERSION": "command_models",
    "ALLOWED_COMMAND_TYPES": "command_models",
    "ALLOWED_EVENT_TYPES": "command_models",
    "ALLOWED_EVENT_STATUSES": "command_models",
    "CommandDraft": "command_models",
    "OperatorApproval": "command_models",
    "ApprovedCommand": "command_models",
    "CommandResult": "command_models",
    "CommandEvent": "command_models",
    "CONTROL_CENTER_COMMAND_VALIDATION_SCHEMA_VERSION": "command_validation",
    "validate_command_type": "command_validation",
    "validate_command_args": "command_validation",
    "validate_no_forbidden_command_text": "command_validation",
    "validate_command_draft": "command_validation",
    "CONTROL_CENTER_OPERATOR_APPROVAL_SCHEMA_VERSION": "operator_approval",
    "approve_command": "operator_approval",
    "reject_command": "operator_approval",
    "create_approved_command": "operator_approval",
    "CONTROL_CENTER_COMMAND_QUEUE_SCHEMA_VERSION": "command_queue",
    "append_approved_command": "command_queue",
    "read_command_queue": "command_queue",
    "CONTROL_CENTER_EVENT_LOG_SCHEMA_VERSION": "event_log",
    "append_command_event": "event_log",
    "read_command_events": "event_log",
    "make_command_event": "event_log",
    "CONTROL_CENTER_COMMAND_RUNNER_SCHEMA_VERSION": "command_runner",
    "run_approved_command": "command_runner",
    "AI_WORK_SESSION_SCHEMA_VERSION": "work_session_models",
    "ALLOWED_AGENT_NAMES": "work_session_models",
    "ALLOWED_RUNTIME_TYPES": "work_session_models",
    "ALLOWED_TASK_TYPES": "work_session_models",
    "ALLOWED_PRIORITIES": "work_session_models",
    "ALLOWED_SESSION_STATUSES": "work_session_models",
    "MANUAL_CLIPBOARD_RUNTIME_ID": "work_session_models",
    "AgentRuntime": "work_session_models",
    "AIWorkTask": "work_session_models",
    "AgentAssignment": "work_session_models",
    "AIWorkSession": "work_session_models",
    "AIWorkSessionError": "work_session_models",
    "RUNTIME_REGISTRY_SCHEMA_VERSION": "runtime_registry",
    "list_runtimes": "runtime_registry",
    "get_runtime": "runtime_registry",
    "find_runtimes_for_task": "runtime_registry",
    "WORK_SESSION_MANAGER_SCHEMA_VERSION": "work_session_manager",
    "ALLOWED_TRANSITIONS": "work_session_manager",
    "TERMINAL_STATUSES": "work_session_manager",
    "validate_transition": "work_session_manager",
    "create_work_session": "work_session_manager",
    "assign_runtime": "work_session_manager",
    "transition_status": "work_session_manager",
    "complete_session": "work_session_manager",
    "cancel_session": "work_session_manager",
    "WORK_SESSION_STORE_SCHEMA_VERSION": "work_session_store",
    "append_session": "work_session_store",
    "append_event": "work_session_store",
    "load_sessions": "work_session_store",
    "load_session": "work_session_store",
    "list_sessions": "work_session_store",
    "AI_AGENT_ADAPTER_SCHEMA_VERSION": "agent_adapter_models",
    "ALLOWED_ADAPTER_AGENT_NAMES": "agent_adapter_models",
    "ALLOWED_ADAPTER_RUNTIME_TYPES": "agent_adapter_models",
    "ALLOWED_ADAPTER_TASK_TYPES": "agent_adapter_models",
    "ALLOWED_DELIVERY_MODES": "agent_adapter_models",
    "ALLOWED_RESULT_TYPES": "agent_adapter_models",
    "ALLOWED_ADAPTER_STATUSES": "agent_adapter_models",
    "ALLOWED_ADAPTER_ERROR_KINDS": "agent_adapter_models",
    "ALLOWED_ADAPTER_EVENT_TYPES": "agent_adapter_models",
    "AgentAdapterCapability": "agent_adapter_models",
    "AgentAdapterRequest": "agent_adapter_models",
    "AgentAdapterResult": "agent_adapter_models",
    "AgentAdapterError": "agent_adapter_models",
    "AgentAdapterSimulationEvent": "agent_adapter_models",
    "AGENT_ADAPTER_CONTRACT_SCHEMA_VERSION": "agent_adapter_contracts",
    "BaseAgentAdapter": "agent_adapter_contracts",
    "ChatGPTContractAdapter": "agent_adapter_contracts",
    "ClaudeCodeContractAdapter": "agent_adapter_contracts",
    "CodexContractAdapter": "agent_adapter_contracts",
    "HermesContractAdapter": "agent_adapter_contracts",
    "ManualClipboardContractAdapter": "agent_adapter_contracts",
    "AGENT_ADAPTER_REGISTRY_SCHEMA_VERSION": "agent_adapter_registry",
    "MANUAL_CLIPBOARD_AGENT_NAME": "agent_adapter_registry",
    "AgentAdapterRegistry": "agent_adapter_registry",
    "create_default_agent_adapter_registry": "agent_adapter_registry",
    "AGENT_ADAPTER_SIMULATOR_SCHEMA_VERSION": "agent_adapter_simulator",
    "simulate_agent_adapter_request": "agent_adapter_simulator",
    "simulate_adapter_lifecycle": "agent_adapter_simulator",
    "PROMPT_RESULT_PACKET_SCHEMA_VERSION": "prompt_result_packet_models",
    "ALLOWED_PACKET_CONTEXT_REF_TYPES": "prompt_result_packet_models",
    "ALLOWED_PACKET_TYPES": "prompt_result_packet_models",
    "ALLOWED_PACKET_AGENT_NAMES": "prompt_result_packet_models",
    "ALLOWED_PROMPT_PACKET_STATUSES": "prompt_result_packet_models",
    "ALLOWED_RESULT_ARTIFACT_TYPES": "prompt_result_packet_models",
    "ALLOWED_RESULT_TYPES_PACKET": "prompt_result_packet_models",
    "ALLOWED_RESULT_VERDICTS": "prompt_result_packet_models",
    "ALLOWED_RESULT_PACKET_STATUSES": "prompt_result_packet_models",
    "ALLOWED_ROUTING_PRIORITIES": "prompt_result_packet_models",
    "ALLOWED_PACKET_ERROR_KINDS": "prompt_result_packet_models",
    "PacketContextReference": "prompt_result_packet_models",
    "PromptPacket": "prompt_result_packet_models",
    "ResultArtifactReference": "prompt_result_packet_models",
    "ResultPacket": "prompt_result_packet_models",
    "PacketRoutingDecision": "prompt_result_packet_models",
    "PromptResultPacketError": "prompt_result_packet_models",
    "PROMPT_RESULT_PACKET_BUILDER_SCHEMA_VERSION": "prompt_result_packet_builder",
    "create_prompt_packet": "prompt_result_packet_builder",
    "create_result_packet": "prompt_result_packet_builder",
    "create_routing_decision": "prompt_result_packet_builder",
    "create_followup_prompt_from_result": "prompt_result_packet_builder",
    "recommend_routing": "prompt_result_packet_builder",
    "PROMPT_RESULT_PACKET_STORE_SCHEMA_VERSION": "prompt_result_packet_store",
    "DEFAULT_PROMPT_PACKETS_PATH": "prompt_result_packet_store",
    "DEFAULT_RESULT_PACKETS_PATH": "prompt_result_packet_store",
    "DEFAULT_PACKET_ROUTING_DECISIONS_PATH": "prompt_result_packet_store",
    "append_prompt_packet": "prompt_result_packet_store",
    "append_result_packet": "prompt_result_packet_store",
    "append_packet_routing_decision": "prompt_result_packet_store",
    "load_prompt_packets": "prompt_result_packet_store",
    "load_result_packets": "prompt_result_packet_store",
    "load_packet_routing_decisions": "prompt_result_packet_store",
    "OPERATOR_PACKET_REVIEW_SCHEMA_VERSION": "operator_packet_review_models",
    "ALLOWED_REVIEW_CHECK_STATUSES": "operator_packet_review_models",
    "ALLOWED_REVIEW_CHECK_SEVERITIES": "operator_packet_review_models",
    "ALLOWED_OPERATOR_PACKET_DECISIONS": "operator_packet_review_models",
    "ALLOWED_OPERATOR_DECIDED_BY": "operator_packet_review_models",
    "ALLOWED_REVIEW_AGENT_NAMES": "operator_packet_review_models",
    "ALLOWED_HANDOFF_MODES": "operator_packet_review_models",
    "ALLOWED_REVIEW_ERROR_KINDS": "operator_packet_review_models",
    "FrozenMap": "operator_packet_review_models",
    "PacketReviewCheck": "operator_packet_review_models",
    "OperatorPacketDecision": "operator_packet_review_models",
    "ManualHandoffInstruction": "operator_packet_review_models",
    "ManualHandoffPackage": "operator_packet_review_models",
    "OperatorPacketReviewResult": "operator_packet_review_models",
    "OperatorPacketReviewError": "operator_packet_review_models",
    "MANUAL_HANDOFF_PACKAGE_SCHEMA_VERSION": "manual_handoff_package",
    "create_manual_handoff_package": "manual_handoff_package",
    "OPERATOR_PACKET_REVIEW_LOGIC_SCHEMA_VERSION": "operator_packet_review",
    "validate_packet_for_operator_review": "operator_packet_review",
    "review_prompt_packet": "operator_packet_review",
    "review_result_packet": "operator_packet_review",
    "OPERATOR_PACKET_REVIEW_STORE_SCHEMA_VERSION": "operator_packet_review_store",
    "DEFAULT_OPERATOR_PACKET_DECISIONS_PATH": "operator_packet_review_store",
    "DEFAULT_OPERATOR_PACKET_REVIEW_RESULTS_PATH": "operator_packet_review_store",
    "DEFAULT_MANUAL_HANDOFFS_DIR": "operator_packet_review_store",
    "append_operator_packet_decision": "operator_packet_review_store",
    "append_operator_packet_review_result": "operator_packet_review_store",
    "load_operator_packet_decisions": "operator_packet_review_store",
    "load_operator_packet_review_results": "operator_packet_review_store",
    "AI_RESULT_INTAKE_SCHEMA_VERSION": "result_intake_models",
    "ALLOWED_ARTIFACT_TYPES": "result_intake_models",
    "ALLOWED_SOURCE_AGENTS": "result_intake_models",
    "ALLOWED_VERDICTS": "result_intake_models",
    "ALLOWED_CONFIDENCE_LEVELS": "result_intake_models",
    "ALLOWED_INTAKE_STATUSES": "result_intake_models",
    "ALLOWED_CHATGPT_TARGET_AGENTS": "result_intake_models",
    "ALLOWED_CHATGPT_ACTIONS": "result_intake_models",
    "ALLOWED_TASK_STATUSES": "result_intake_models",
    "ALLOWED_STAGE_STATUSES": "result_intake_models",
    "ALLOWED_NEXT_ACTIONS": "result_intake_models",
    "ALLOWED_NEXT_ACTION_PRIORITIES": "result_intake_models",
    "ALLOWED_INTAKE_ERROR_KINDS": "result_intake_models",
    "ResultIntakeArtifact": "result_intake_models",
    "AIResultIntakeRecord": "result_intake_models",
    "ChatGPTStatusUpdatePacket": "result_intake_models",
    "ProjectStateUpdate": "result_intake_models",
    "NextActionDecision": "result_intake_models",
    "AIResultIntakeError": "result_intake_models",
    "RESULT_INTAKE_BUILDER_SCHEMA_VERSION": "result_intake_builder",
    "classify_verdict": "result_intake_builder",
    "build_result_intake_record": "result_intake_builder",
    "build_chatgpt_status_update_packet": "result_intake_builder",
    "build_project_state_update": "result_intake_builder",
    "build_next_action_decision": "result_intake_builder",
    "RESULT_INTAKE_STORE_SCHEMA_VERSION": "result_intake_store",
    "ResultIntakeStore": "result_intake_store",
    "CHATGPT_STATUS_UPDATE_SCHEMA_VERSION": "chatgpt_status_update",
    "prepare_chatgpt_status_update": "chatgpt_status_update",
    "render_chatgpt_status_update_markdown": "chatgpt_status_update",
    "PROJECT_STATE_UPDATE_SCHEMA_VERSION": "project_state_update",
    "prepare_project_state_update": "project_state_update",
    "prepare_next_action_decision": "project_state_update",
    "render_project_state_summary": "project_state_update",
    "GIT_APPROVAL_SCHEMA_VERSION": "git_approval_models",
    "ALLOWED_CHANGE_TYPES": "git_approval_models",
    "ALLOWED_TEST_EVIDENCE_STATUSES": "git_approval_models",
    "ALLOWED_RISK_LEVELS": "git_approval_models",
    "ALLOWED_APPROVAL_DECISIONS": "git_approval_models",
    "ALLOWED_GIT_APPROVAL_EVENT_TYPES": "git_approval_models",
    "ALLOWED_GIT_APPROVAL_ERROR_KINDS": "git_approval_models",
    "GitChangedFile": "git_approval_models",
    "GitTestEvidence": "git_approval_models",
    "GitEvidenceSnapshot": "git_approval_models",
    "CommitProposal": "git_approval_models",
    "CommitApprovalDecision": "git_approval_models",
    "PushReadinessSnapshot": "git_approval_models",
    "PushProposal": "git_approval_models",
    "PushApprovalDecision": "git_approval_models",
    "GitApprovalEvent": "git_approval_models",
    "GitApprovalError": "git_approval_models",
    "GIT_EVIDENCE_SNAPSHOT_SCHEMA_VERSION": "git_evidence_snapshot",
    "build_git_evidence_snapshot": "git_evidence_snapshot",
    "build_push_readiness_snapshot": "git_evidence_snapshot",
    "GIT_APPROVAL_BUILDER_SCHEMA_VERSION": "git_approval_builder",
    "build_commit_proposal": "git_approval_builder",
    "record_commit_approval_decision": "git_approval_builder",
    "build_push_proposal": "git_approval_builder",
    "record_push_approval_decision": "git_approval_builder",
    "build_git_approval_event": "git_approval_builder",
    "GIT_APPROVAL_STORE_SCHEMA_VERSION": "git_approval_store",
    "GitApprovalStore": "git_approval_store",
    # Stage 5.9 - Local Operator Execution Console / Manual Command Runbook
    "OPERATOR_EXECUTION_SCHEMA_VERSION": "operator_execution_models",
    "ALLOWED_COMMAND_TYPES": "operator_execution_models",
    "ALLOWED_SHELLS": "operator_execution_models",
    "ALLOWED_SAFETY_CHECK_STATUSES": "operator_execution_models",
    "ALLOWED_SAFETY_CHECK_SEVERITIES": "operator_execution_models",
    "ALLOWED_RUNBOOK_TYPES": "operator_execution_models",
    "ALLOWED_RUNBOOK_STATUSES": "operator_execution_models",
    "ALLOWED_CAPTURE_VERDICTS": "operator_execution_models",
    "ALLOWED_OUTCOMES": "operator_execution_models",
    "ALLOWED_NEXT_AGENTS": "operator_execution_models",
    "ALLOWED_OPERATOR_EXECUTION_ERROR_KINDS": "operator_execution_models",
    "RunbookCommandStep": "operator_execution_models",
    "ExecutionSafetyCheck": "operator_execution_models",
    "ManualCommandRunbook": "operator_execution_models",
    "CommandExecutionCapture": "operator_execution_models",
    "OperatorExecutionOutcome": "operator_execution_models",
    "OperatorExecutionError": "operator_execution_models",
    "OPERATOR_EXECUTION_RUNBOOK_SCHEMA_VERSION": "operator_execution_runbook",
    "create_manual_command_runbook": "operator_execution_runbook",
    "create_git_commit_runbook": "operator_execution_runbook",
    "create_git_push_runbook": "operator_execution_runbook",
    "capture_manual_command_result": "operator_execution_runbook",
    "classify_operator_execution_outcome": "operator_execution_runbook",
    "OPERATOR_EXECUTION_STORE_SCHEMA_VERSION": "operator_execution_store",
    "append_manual_command_runbook": "operator_execution_store",
    "append_command_execution_capture": "operator_execution_store",
    "append_operator_execution_outcome": "operator_execution_store",
    "load_manual_command_runbooks": "operator_execution_store",
    "load_command_execution_captures": "operator_execution_store",
    "load_operator_execution_outcomes": "operator_execution_store",
}

__all__ = sorted(_LAZY_EXPORTS)


def __getattr__(name: str) -> Any:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from importlib import import_module

    module = import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
